parameters:
    pim_datagrid.normalizer.datagrid_view.class: Pim\Bundle\DataGridBundle\Normalizer\DatagridViewNormalizer

services:
    pim_datagrid.normalizer.datagrid_view:
        class: '%pim_datagrid.normalizer.datagrid_view.class%'
        tags:
            - { name: pim_internal_api_serializer.normalizer }
